version: '3.9'

services:
    database:
        image: 'mariadb:10.7.3'
        container_name: ecf-database-container
        restart: 'on-failure'
        volumes:
            - '.:/srv:cached'
        ports:
            - "3300:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: ecf-api

    phpmyadmin:
        image: phpmyadmin
        container_name: ecf-phpmyadmin-container
        restart: always
        ports:
            - 8080:80
        links:
            - 'database'
        environment:
            - PMA_ARBITRARY=1

networks: 
    default:
        name: ecf-back-network